### ISSUE TITLE
Exception during JIRA startup.

### ISSUE THREAD

**Issue by steigr** [MIDAN-SOFTWARE/MIDANAuthenticator#3]
JIRA Core 7.3.6 + JIRA Servicedesk 3.5.0

I got the following exception when my JIRA instance starts:

```
2017-05-06 17:00:47,156 localhost-startStop-1 ERROR      [o.a.c.c.C.[Catalina].[localhost].[/]] Exception starting filter security
java.lang.ExceptionInInitializerError
        at com.atlassian.jira.security.login.SSOSeraphAuthenticator.<init>(SSOSeraphAuthenticator.java:30)
        at eu.midan.SSOAuthenticatorWrapper.<init>(SSOAuthenticatorWrapper.java:37)
        at eu.midan.MIDANAuthenticator.<init>(MIDANAuthenticator.java:52)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        ... 1 filtered
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at java.lang.Class.newInstance(Class.java:442)
        at com.atlassian.seraph.config.SecurityConfigImpl.configureClass(SecurityConfigImpl.java:320)
        at com.atlassian.seraph.config.SecurityConfigImpl.configureAuthenticator(SecurityConfigImpl.java:258)
        at com.atlassian.seraph.config.SecurityConfigImpl.<init>(SecurityConfigImpl.java:194)
        at com.atlassian.seraph.config.SecurityConfigFactory.loadInstance(SecurityConfigFactory.java:56)
        at com.atlassian.seraph.config.SecurityConfigFactory.getInstance(SecurityConfigFactory.java:39)
        ... 1 filtered
        at com.atlassian.jira.security.JiraSecurityFilter.init(JiraSecurityFilter.java:42)
        at com.atlassian.jira.security.JiraSecurityFilter.init(JiraSecurityFilter.java:36)
        ... 8 filtered
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NullPointerException
        at java.net.URI$Parser.parse(URI.java:3042)
        at java.net.URI.<init>(URI.java:588)
        at com.atlassian.crowd.integration.rest.service.DefaultHttpClientProvider.routeFor(DefaultHttpClientProvider.java:107)
        at com.atlassian.crowd.integration.rest.service.DefaultHttpClientProvider.getClient(DefaultHttpClientProvider.java:53)
        at com.atlassian.crowd.integration.rest.service.factory.RestCrowdClientFactory.getHttpClient(RestCrowdClientFactory.java:89)
        at com.atlassian.crowd.integration.rest.service.factory.RestCrowdHttpAuthenticationFactory.createInstance(RestCrowdHttpAuthenticationFactory.java:43)
        at com.atlassian.crowd.integration.rest.service.factory.RestCrowdHttpAuthenticationFactory.<clinit>(RestCrowdHttpAuthenticationFactory.java:21)
        ... 28 more
2017-05-06 17:00:47,202 localhost-startStop-1 ERROR      [o.a.c.c.C.[Catalina].[localhost].[/]] Exception starting filter trustedapps
java.lang.NoClassDefFoundError: Could not initialize class com.atlassian.crowd.integration.rest.service.factory.RestCrowdHttpAuthenticationFactory
        at com.atlassian.jira.security.login.SSOSeraphAuthenticator.<init>(SSOSeraphAuthenticator.java:30)
        at eu.midan.SSOAuthenticatorWrapper.<init>(SSOAuthenticatorWrapper.java:37)
        at eu.midan.MIDANAuthenticator.<init>(MIDANAuthenticator.java:52)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        ... 1 filtered
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at java.lang.Class.newInstance(Class.java:442)
        at com.atlassian.seraph.config.SecurityConfigImpl.configureClass(SecurityConfigImpl.java:320)
        at com.atlassian.seraph.config.SecurityConfigImpl.configureAuthenticator(SecurityConfigImpl.java:258)
        at com.atlassian.seraph.config.SecurityConfigImpl.<init>(SecurityConfigImpl.java:194)
        at com.atlassian.seraph.config.SecurityConfigFactory.loadInstance(SecurityConfigFactory.java:56)
        at com.atlassian.seraph.config.SecurityConfigFactory.getInstance(SecurityConfigFactory.java:21)
        at com.atlassian.security.auth.trustedapps.seraph.filter.SeraphTrustedApplicationsFilter.<init>(SeraphTrustedApplicationsFilter.java:16)
        ... 1 filtered
        at com.atlassian.jira.security.auth.trustedapps.TrustedApplicationFilter.<init>(TrustedApplicationFilter.java:25)
        ... 3 filtered
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at java.lang.Class.newInstance(Class.java:442)
        ... 8 filtered
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:748)
```

I did not  try to recompile or something, but I guess that there is some API change.

**Comment by marcelwirtz** [comment]
@steigr i've updated our JIRA installation to JIRA Core 7.3.6 + ServiceDesk 3.5.0 and installed the authenticator of our release 1.1 on github and it works without any errors.

Can you provide additional information about your setup? Does crowd properly work without our authenticator and have you configured your jira to use crowd sso?

Kind regards,
Marcel

**Comment by steigr** [comment]
I investigated this issue a little bit. At first: it's working now! :-)

I had disabled the internal directory. After reenabling the Exceptions went away, but my customers were still not able to log in until I set the JIRA Internal Directory as first User directory. There may be an issue but I'm not sure about that. I thank you for your quick response.

**Comment by marcelwirtz** [comment]
Thanks for sharing the issue you had, i have updated the readme and mentioned it there.
